### ISSUE TITLE
node_modules in the project root

### ISSUE THREAD

**Issue by Karyum** [FACN7/aom-tdd-week3#6]
node_modules is a huge folder, and you don't really need it in the github repo because you could always get it when you do `npm install`. being a huge folder makes it take ages to clone or install a project so we always add node_modules to the .gitignore.

so remove it from the root directory :sweat_smile:

**Comment by Karyum** [comment]
https://git-scm.com/docs/gitignore

**Comment by mcorcias** [comment]
fixed

**Comment by Karyum** [comment]
it's still not fixed, you didn't merge the branch im guessing
